name: Feature Request
description: Request a new feature or improvement.
title: "[Feature]: "
labels: ["feature", "triage", "feature-request"]
body:
  - type: markdown
    attributes:
      value: "Thank you for suggesting a new feature. Please explain your idea clearly."
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe it.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution or new feature you would like to see.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
